In [5]:
import os
home=os.path.expanduser("~")

In [6]:
import findspark
findspark.init(os.path.join(home,"Developer","spark-2.0.0-bin-hadoop2.6"))

In [7]:
import pyspark
myConf=pyspark.SparkConf()
spark = pyspark.sql.SparkSession.builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

In [1]:
dv1=[0.0, 1.1, 0.1]
print dv1, type(dv1)

[0.0, 1.1, 0.1] <type 'list'>


In [8]:
import numpy as np

dv2 = np.array([1.0, 2.1, 3.2])

In [9]:
from pyspark.mllib.linalg import Vectors
dv1mllib=Vectors.dense(dv1)
print dv1mllib, type(dv1mllib)

[0.0,1.1,0.1] <class 'pyspark.mllib.linalg.DenseVector'>


In [10]:
from pyspark.ml.linalg import Vectors
dv1ml=Vectors.dense(dv1)
print dv1ml

[0.0,1.1,0.1]


In [11]:
for e in dv1ml:
    print e,

0.0 1.1 0.1


In [12]:
import numpy as np
import scipy.sparse as sps

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = sps.csc_matrix((data, (row, col)), shape=(3, 3))
print mtx.todense()  

[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [13]:
from pyspark.mllib.regression import LabeledPoint
print LabeledPoint(1.0, [1.0, 2.0, 3.0])

(1.0,[1.0,2.0,3.0])


In [14]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors

print LabeledPoint(1992, Vectors.sparse(10, {0: 3.0, 1:5.5, 2: 10.0}))

(1992.0,(10,[0,1,2],[3.0,5.5,10.0]))


In [15]:
from pyspark.mllib.regression import LabeledPoint
LabeledPoint(1.0, dv1mllib)

LabeledPoint(1.0, [0.0,1.1,0.1])

In [16]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors
LabeledPoint(1.0, Vectors.fromML(dv1ml))

LabeledPoint(1.0, [0.0,1.1,0.1])

In [17]:
p = [[1,[1.0,2.0,3.0]],[1,[1.1,2.1,3.1]],[0,[1.2,2.2,3.3]]]
trainDf=spark.createDataFrame(p)
trainDf.collect()

[Row(_1=1, _2=[1.0, 2.0, 3.0]),
 Row(_1=1, _2=[1.1, 2.1, 3.1]),
 Row(_1=0, _2=[1.2, 2.2, 3.3])]

In [18]:
from pyspark.mllib.regression import LabeledPoint
p = [LabeledPoint(1,[1.0,2.0,3.0]),
     LabeledPoint(1,[1.1,2.1,3.1]),
     LabeledPoint(0,[1.2,2.2,3.3])]
trainDf=spark.createDataFrame(p)
trainDf.collect()

[Row(features=DenseVector([1.0, 2.0, 3.0]), label=1.0),
 Row(features=DenseVector([1.1, 2.1, 3.1]), label=1.0),
 Row(features=DenseVector([1.2, 2.2, 3.3]), label=0.0)]